// <auto-generated />
using System;
using Iroh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iroh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iroh.Data.Description", b =>
                {
                    b.Property<int>("ThingId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ThingId", "TagId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("Iroh.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Family")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Family = 0,
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 2,
                            Family = 0,
                            Name = "Sculpture"
                        },
                        new
                        {
                            Id = 3,
                            Family = 0,
                            Name = "Theatre Act"
                        },
                        new
                        {
                            Id = 4,
                            Family = 1,
                            Name = "Ancient Civilization"
                        },
                        new
                        {
                            Id = 5,
                            Family = 1,
                            Name = "Archaeological Site"
                        },
                        new
                        {
                            Id = 6,
                            Family = 1,
                            Name = "Battlefield"
                        },
                        new
                        {
                            Id = 7,
                            Family = 1,
                            Name = "Building"
                        },
                        new
                        {
                            Id = 8,
                            Family = 1,
                            Name = "Landmark"
                        },
                        new
                        {
                            Id = 9,
                            Family = 1,
                            Name = "Memorial"
                        },
                        new
                        {
                            Id = 10,
                            Family = 1,
                            Name = "Monument"
                        },
                        new
                        {
                            Id = 11,
                            Family = 1,
                            Name = "Palace or Castle"
                        },
                        new
                        {
                            Id = 12,
                            Family = 1,
                            Name = "Religious Site"
                        },
                        new
                        {
                            Id = 13,
                            Family = 1,
                            Name = "Ruins"
                        },
                        new
                        {
                            Id = 14,
                            Family = 2,
                            Name = "Activist"
                        },
                        new
                        {
                            Id = 15,
                            Family = 2,
                            Name = "Actor"
                        },
                        new
                        {
                            Id = 16,
                            Family = 2,
                            Name = "Artist"
                        },
                        new
                        {
                            Id = 17,
                            Family = 2,
                            Name = "Athlete"
                        },
                        new
                        {
                            Id = 18,
                            Family = 2,
                            Name = "Author"
                        },
                        new
                        {
                            Id = 19,
                            Family = 2,
                            Name = "Businessman"
                        },
                        new
                        {
                            Id = 20,
                            Family = 2,
                            Name = "Musician"
                        },
                        new
                        {
                            Id = 21,
                            Family = 2,
                            Name = "Philosopher"
                        },
                        new
                        {
                            Id = 22,
                            Family = 2,
                            Name = "Politician"
                        },
                        new
                        {
                            Id = 23,
                            Family = 2,
                            Name = "Scientist"
                        },
                        new
                        {
                            Id = 24,
                            Family = 2,
                            Name = "Writer"
                        },
                        new
                        {
                            Id = 25,
                            Family = 2,
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = 26,
                            Family = 3,
                            Name = "Amphibian"
                        },
                        new
                        {
                            Id = 27,
                            Family = 3,
                            Name = "Bird"
                        },
                        new
                        {
                            Id = 28,
                            Family = 3,
                            Name = "Insect"
                        },
                        new
                        {
                            Id = 29,
                            Family = 3,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 30,
                            Family = 3,
                            Name = "Mammal"
                        },
                        new
                        {
                            Id = 31,
                            Family = 3,
                            Name = "Reptile"
                        },
                        new
                        {
                            Id = 32,
                            Family = 4,
                            Name = "Battles"
                        },
                        new
                        {
                            Id = 33,
                            Family = 4,
                            Name = "Discovery"
                        },
                        new
                        {
                            Id = 34,
                            Family = 4,
                            Name = "Holiday"
                        },
                        new
                        {
                            Id = 35,
                            Family = 4,
                            Name = "Invention"
                        },
                        new
                        {
                            Id = 36,
                            Family = 4,
                            Name = "Natural Disaster"
                        },
                        new
                        {
                            Id = 37,
                            Family = 4,
                            Name = "Political Action"
                        },
                        new
                        {
                            Id = 38,
                            Family = 4,
                            Name = "Revolution or Civil War"
                        },
                        new
                        {
                            Id = 39,
                            Family = 4,
                            Name = "War"
                        },
                        new
                        {
                            Id = 40,
                            Family = 4,
                            Name = "Other Event"
                        },
                        new
                        {
                            Id = 41,
                            Family = 7,
                            Name = "Anecdote"
                        },
                        new
                        {
                            Id = 42,
                            Family = 7,
                            Name = "Article"
                        },
                        new
                        {
                            Id = 43,
                            Family = 7,
                            Name = "Book"
                        },
                        new
                        {
                            Id = 44,
                            Family = 7,
                            Name = "Essay"
                        },
                        new
                        {
                            Id = 45,
                            Family = 7,
                            Name = "Legend"
                        },
                        new
                        {
                            Id = 46,
                            Family = 7,
                            Name = "Paper"
                        },
                        new
                        {
                            Id = 47,
                            Family = 7,
                            Name = "Poem"
                        },
                        new
                        {
                            Id = 48,
                            Family = 7,
                            Name = "Quote"
                        },
                        new
                        {
                            Id = 49,
                            Family = 7,
                            Name = "Series of Writings"
                        },
                        new
                        {
                            Id = 50,
                            Family = 7,
                            Name = "Tale"
                        },
                        new
                        {
                            Id = 51,
                            Family = 7,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 52,
                            Family = 7,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 53,
                            Family = 6,
                            Name = "Album"
                        },
                        new
                        {
                            Id = 54,
                            Family = 6,
                            Name = "Mixtape"
                        },
                        new
                        {
                            Id = 55,
                            Family = 6,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 56,
                            Family = 5,
                            Name = "Anime"
                        },
                        new
                        {
                            Id = 57,
                            Family = 5,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = 58,
                            Family = 5,
                            Name = "Series"
                        },
                        new
                        {
                            Id = 59,
                            Family = 5,
                            Name = "Shortmovie"
                        },
                        new
                        {
                            Id = 60,
                            Family = 5,
                            Name = "Other Video"
                        },
                        new
                        {
                            Id = 61,
                            Family = 8,
                            Name = "Board"
                        },
                        new
                        {
                            Id = 62,
                            Family = 8,
                            Name = "Card"
                        },
                        new
                        {
                            Id = 63,
                            Family = 8,
                            Name = "Party"
                        },
                        new
                        {
                            Id = 64,
                            Family = 8,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 65,
                            Family = 10,
                            Name = "Home Utility"
                        },
                        new
                        {
                            Id = 66,
                            Family = 10,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 67,
                            Family = 10,
                            Name = "Labor Utility"
                        },
                        new
                        {
                            Id = 68,
                            Family = 10,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 69,
                            Family = 10,
                            Name = "Quality of Life"
                        },
                        new
                        {
                            Id = 70,
                            Family = 10,
                            Name = "Universal Utility"
                        },
                        new
                        {
                            Id = 71,
                            Family = 10,
                            Name = "Chemical"
                        },
                        new
                        {
                            Id = 89,
                            Family = 101,
                            Name = "Archaeology"
                        },
                        new
                        {
                            Id = 90,
                            Family = 101,
                            Name = "Astrology:)"
                        },
                        new
                        {
                            Id = 91,
                            Family = 101,
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = 92,
                            Family = 101,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 93,
                            Family = 101,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 94,
                            Family = 101,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 95,
                            Family = 101,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 96,
                            Family = 101,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 97,
                            Family = 101,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 98,
                            Family = 101,
                            Name = "Sociology"
                        },
                        new
                        {
                            Id = 99,
                            Family = 102,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 100,
                            Family = 102,
                            Name = "Car Racing"
                        },
                        new
                        {
                            Id = 101,
                            Family = 102,
                            Name = "Esports"
                        },
                        new
                        {
                            Id = 102,
                            Family = 102,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 103,
                            Family = 102,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 104,
                            Family = 102,
                            Name = "Rugby or American Football"
                        },
                        new
                        {
                            Id = 105,
                            Family = 102,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 106,
                            Family = 102,
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = 107,
                            Family = 102,
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = 108,
                            Family = 102,
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = 109,
                            Family = 102,
                            Name = "Weightlifting"
                        },
                        new
                        {
                            Id = 110,
                            Family = 102,
                            Name = "Other Sport"
                        },
                        new
                        {
                            Id = 111,
                            Family = 100,
                            Name = "About Children"
                        },
                        new
                        {
                            Id = 112,
                            Family = 100,
                            Name = "Advice"
                        },
                        new
                        {
                            Id = 113,
                            Family = 100,
                            Name = "Art or Photography"
                        },
                        new
                        {
                            Id = 114,
                            Family = 100,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 115,
                            Family = 100,
                            Name = "Commentary"
                        },
                        new
                        {
                            Id = 116,
                            Family = 100,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 117,
                            Family = 100,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 118,
                            Family = 100,
                            Name = "Guide"
                        },
                        new
                        {
                            Id = 119,
                            Family = 100,
                            Name = "Memoir"
                        },
                        new
                        {
                            Id = 120,
                            Family = 100,
                            Name = "Parenting"
                        },
                        new
                        {
                            Id = 121,
                            Family = 100,
                            Name = "Past Civilization"
                        },
                        new
                        {
                            Id = 122,
                            Family = 100,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 123,
                            Family = 100,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 124,
                            Family = 100,
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 125,
                            Family = 100,
                            Name = "Personal Relationship"
                        },
                        new
                        {
                            Id = 126,
                            Family = 100,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 127,
                            Family = 100,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 128,
                            Family = 100,
                            Name = "True Crime"
                        },
                        new
                        {
                            Id = 129,
                            Family = 103,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 130,
                            Family = 103,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 131,
                            Family = 103,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 132,
                            Family = 103,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 133,
                            Family = 103,
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 134,
                            Family = 103,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 135,
                            Family = 103,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 136,
                            Family = 103,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 137,
                            Family = 103,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 138,
                            Family = 103,
                            Name = "Noir"
                        },
                        new
                        {
                            Id = 139,
                            Family = 103,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 140,
                            Family = 103,
                            Name = "Satire"
                        },
                        new
                        {
                            Id = 141,
                            Family = 103,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 142,
                            Family = 103,
                            Name = "Seinen"
                        },
                        new
                        {
                            Id = 143,
                            Family = 103,
                            Name = "Shoji"
                        },
                        new
                        {
                            Id = 144,
                            Family = 103,
                            Name = "Shonen"
                        },
                        new
                        {
                            Id = 145,
                            Family = 103,
                            Name = "Swashbuckle"
                        },
                        new
                        {
                            Id = 146,
                            Family = 103,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 147,
                            Family = 104,
                            Name = "Fun or Comedy"
                        },
                        new
                        {
                            Id = 148,
                            Family = 104,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 149,
                            Family = 104,
                            Name = "Safe For Children"
                        },
                        new
                        {
                            Id = 150,
                            Family = 104,
                            Name = "Was Banned Somewhere"
                        },
                        new
                        {
                            Id = 151,
                            Family = 105,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 152,
                            Family = 105,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 153,
                            Family = 105,
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            Id = 154,
                            Family = 105,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 155,
                            Family = 105,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 156,
                            Family = 105,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 157,
                            Family = 105,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 158,
                            Family = 105,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 159,
                            Family = 105,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 160,
                            Family = 105,
                            Name = "Soundtrack"
                        },
                        new
                        {
                            Id = 161,
                            Family = 106,
                            Name = "2D"
                        },
                        new
                        {
                            Id = 162,
                            Family = 106,
                            Name = "3D"
                        },
                        new
                        {
                            Id = 163,
                            Family = 106,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 164,
                            Family = 106,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 165,
                            Family = 106,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            Id = 166,
                            Family = 106,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 167,
                            Family = 106,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 168,
                            Family = 106,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 169,
                            Family = 106,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 900,
                            Family = 200,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 901,
                            Family = 200,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 902,
                            Family = 200,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 903,
                            Family = 200,
                            Name = "Middle East"
                        },
                        new
                        {
                            Id = 904,
                            Family = 200,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 905,
                            Family = 200,
                            Name = "Oceania"
                        },
                        new
                        {
                            Id = 906,
                            Family = 200,
                            Name = "Ocean"
                        },
                        new
                        {
                            Id = 907,
                            Family = 200,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 908,
                            Family = 201,
                            Name = "21th Century"
                        },
                        new
                        {
                            Id = 909,
                            Family = 201,
                            Name = "20th Century"
                        },
                        new
                        {
                            Id = 910,
                            Family = 201,
                            Name = "19th Century"
                        },
                        new
                        {
                            Id = 911,
                            Family = 201,
                            Name = "18th Century"
                        },
                        new
                        {
                            Id = 912,
                            Family = 201,
                            Name = "17th Century"
                        },
                        new
                        {
                            Id = 913,
                            Family = 201,
                            Name = "16th Century"
                        },
                        new
                        {
                            Id = 914,
                            Family = 201,
                            Name = "5th to 15th Century"
                        },
                        new
                        {
                            Id = 915,
                            Family = 201,
                            Name = "Ancient to 4th Century"
                        },
                        new
                        {
                            Id = 916,
                            Family = 201,
                            Name = "Pre Historic"
                        },
                        new
                        {
                            Id = 917,
                            Family = 202,
                            Name = "Factual"
                        },
                        new
                        {
                            Id = 918,
                            Family = 202,
                            Name = "Fictional"
                        },
                        new
                        {
                            Id = 919,
                            Family = 202,
                            Name = "Mythological"
                        },
                        new
                        {
                            Id = 920,
                            Family = 202,
                            Name = "Religious"
                        });
                });

            modelBuilder.Entity("Iroh.Data.Thing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("App")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Things");
                });
#pragma warning restore 612, 618
        }
    }
}
